"""Database models and connection."""
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, JSON, Enum as SQLEnum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import enum

from backend.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Platform(str, enum.Enum):
    KALSHI = "kalshi"
    POLYMARKET = "polymarket"


class MarketCategory(str, enum.Enum):
    WEATHER = "weather"
    ECON = "econ"
    CRYPTO = "crypto"
    POLITICS = "politics"
    OTHER = "other"


class TradeDirection(str, enum.Enum):
    YES = "yes"
    NO = "no"


class TradeResult(str, enum.Enum):
    PENDING = "pending"
    WIN = "win"
    LOSS = "loss"


class Market(Base):
    """Active markets being tracked."""
    __tablename__ = "markets"

    id = Column(Integer, primary_key=True, index=True)
    platform = Column(String, index=True)  # kalshi or polymarket
    ticker = Column(String, unique=True, index=True)
    title = Column(String)
    category = Column(String, index=True)  # weather, econ, etc.
    subcategory = Column(String)  # city name or econ series

    # Market details
    settlement_time = Column(DateTime)
    threshold = Column(Float, nullable=True)  # e.g., 45 for "above 45°F"
    direction = Column(String, nullable=True)  # above/below

    # Current prices
    yes_price = Column(Float)
    no_price = Column(Float)
    volume = Column(Float)
    last_updated = Column(DateTime, default=datetime.utcnow)

    # Our model's view
    model_probability = Column(Float, nullable=True)
    confidence = Column(Float, nullable=True)
    edge = Column(Float, nullable=True)
    data_sources = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    # Signal details
    direction = Column(String)  # yes or no
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    # Kelly sizing
    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    # Data sources used
    sources = Column(JSON)
    reasoning = Column(String)

    # Whether signal was "executed" in simulation
    executed = Column(Boolean, default=False)


class Trade(Base):
    """Simulated trades for tracking P&L."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)

    # Trade details
    direction = Column(String)
    entry_price = Column(Float)
    size = Column(Float)  # in dollars
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Settlement
    settled = Column(Boolean, default=False)
    settlement_time = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)  # 0 or 1
    result = Column(String, default="pending")  # pending, win, loss
    pnl = Column(Float, nullable=True)

    # Model performance tracking
    model_probability = Column(Float)
    market_price_at_entry = Column(Float)
    edge_at_entry = Column(Float)


class WeatherForecast(Base):
    """Cached weather forecasts."""
    __tablename__ = "weather_forecasts"

    id = Column(Integer, primary_key=True, index=True)
    city = Column(String, index=True)
    forecast_date = Column(DateTime, index=True)
    fetched_at = Column(DateTime, default=datetime.utcnow)

    # NWS deterministic
    nws_high = Column(Float, nullable=True)
    nws_low = Column(Float, nullable=True)

    # Ensemble data (stored as JSON)
    ensemble_temps = Column(JSON, nullable=True)  # list of temps from ensemble members
    ensemble_source = Column(String, nullable=True)  # ecmwf, gfs, etc.

    # Calculated probabilities for common thresholds
    prob_above_freezing = Column(Float, nullable=True)
    prob_above_40 = Column(Float, nullable=True)
    prob_above_50 = Column(Float, nullable=True)
    prob_above_60 = Column(Float, nullable=True)
    prob_above_70 = Column(Float, nullable=True)
    prob_above_80 = Column(Float, nullable=True)
    prob_above_90 = Column(Float, nullable=True)


class BotState(Base):
    """Bot state and statistics."""
    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True)
    bankroll = Column(Float, default=10000.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_run = Column(DateTime, nullable=True)
    is_running = Column(Boolean, default=False)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
